### ISSUE TITLE
"Library class doesn't store attributes" when using '-keepkotlinmetadata' option

### ISSUE THREAD

**Issue by adirubin** [Guardsquare/proguard#120]
Hi,
I'm trying to obfuscate some Kotlin code, but I got this error:
_Error: Library class [org/http4k/format/ConfigurableJacksonKt$read$1$1] doesn't store attributes_

Here is my class that triggers the error:

```
class HttpHandler(private val ftInterface: FtInterface) {

    fun getElementData(): ContractRoute {
        val responseLens = Body.auto<DataResult<OutputElementData>>("Element Data").toLens()

        val spec = "/data" meta {
            summary = "Retrieve data"
        } bindContract Method.GET
        val handler: HttpHandler = {request: Request ->
            runBlocking {
                val result = ftInterface.getElementData()
                val res = Response(Status.OK).with(responseLens of result)
                res
            }
        }

        return spec to handler
    }
}
```

[I trimmed the code, so it won't make much sense...]

I did some digging in proguard's code, and it here is what I think happens:
For the code above, the Kotlin compiler generates (among other stuff) this java class:
```
@Metadata(
   mv = {1, 1, 15},
   bv = {1, 0, 3},
   k = 1,
   d1 = {"\u0000\u0011\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\b\u0003*\u0001\u0000\b\n\u0018\u00002\b\u0012\u0004\u0012\u00028\u00000\u0001¨\u0006\u0002¸\u0006\u0004"},
   d2 = {"org/http4k/format/ConfigurableJacksonKt$read$1$1", "Lcom/fasterxml/jackson/core/type/TypeReference;", "http4k-format-jackson", "org/http4k/format/ConfigurableJackson$autoBody$$inlined$read$2$1", "org/http4k/format/ConfigurableJackson$auto$$inlined$autoBody$2$1"}
)
public final class HttpHandler$getElementData$$inlined$auto$1$1 extends TypeReference {
}
```

The Metadata annotation turns into a KotlinClassKindMetadata in proguard, with referencedClass set to the Library class org/http4k/format/ConfigurableJackson$autoBody$$inlined$read$2$1.
Then comes KotlinAnnotationFlagFixer and attempts to visit the referencedClass's attributes, but we get the error because its a library class. I'm no expert in proguard or Kotlin, so take that with a grain of salt...

Here is an example code:
[proguard_kotlin_bug.tar.gz](https://github.com/Guardsquare/proguard/files/5838160/proguard_kotlin_bug.tar.gz)

Steps to reproduce:
```
mvn install
proguard @config.pro
```

Using proguard 7.0.1 and Kotlin 1.3.50. 

I'll be glad for a solution or a workaround.

Thanks!
Adi

**Comment by mrjameshamilton** [comment]
Hi @adirubin! Thanks for your report and detailed analysis! Your analysis sounds correct :)

It's a known issue that previously came up as one of the problems of #94.

It's a limitation right now, since the [`LibraryClass`](https://github.com/Guardsquare/proguard-core/blob/master/src/proguard/classfile/LibraryClass.java)s don't current store 'Attribute's and the
Kotlin metadata is loaded from a class's attributes. We need to change how we load the Kotlin metadata for library classes.

**Comment by adirubin** [comment]
Hi @mrjameshamilton,
Thanks a lot!
So according to #94 a workaround could be to process the Http4k jar as program rather than library?

**Comment by mrjameshamilton** [comment]
@adirubin Indeed, that should work as a workaround, since then they will have all the Kotlin metadata and attributes available when they're read in as a program jar (`ProgramClass`es).

**Comment by adirubin** [comment]
Hi @mrjameshamilton , are these bugs on the roadmap?
Thanks

**Comment by mrjameshamilton** [comment]
Hi @adirubin, unfortunately it's not on the roadmap right now but we're aware of the problem.

**Comment by EGORAGANIN** [comment]
Hi @adirubin this problem actyally when using flow Kotlin Coroutines in every project.

**Comment by ianbrandt** [comment]
@mrjameshamilton,

> It's related to a known issue that previously came up as one of the problems of #94.

So is this issue a duplicate of #94, or is there something that makes it its own separate issue?

**Comment by ketan** [comment]
Is there a workaround for this problem? I'm seeing the following exception when running proguard on a kotlin+springboot project

```
java.lang.UnsupportedOperationException: Library class [com/fasterxml/jackson/module/kotlin/ExtensionsKt$jacksonTypeRef$1] doesn't store attributes
	at proguard.classfile.LibraryClass.attributesAccept(LibraryClass.java:486) ~[proguard-core-9.1.10.jar:9.1.10]
	at proguard.fixer.kotlin.KotlinAnnotationFlagFixer.visitKotlinClassMetadata(KotlinAnnotationFlagFixer.java:74) ~[proguard-base-7.7.0.jar:7.7.0]
	at proguard.classfile.kotlin.KotlinClassKindMetadata.accept(KotlinClassKindMetadata.java:81) ~[proguard-core-9.1.10.jar:9.1.10]
	at proguard.classfile.ProgramClass.kotlinMetadataAccept(ProgramClass.java:628) ~[proguard-core-9.1.10.jar:9.1.10]
	at proguard.classfile.kotlin.visitor.ReferencedKotlinMetadataVisitor.visitProgramClass(ReferencedKotlinMetadataVisitor.java:45) ~[proguard-core-9.1.10.jar:9.1.10]
	at proguard.classfile.ProgramClass.accept(ProgramClass.java:491) ~[proguard-core-9.1.10.jar:9.1.10]
	at proguard.classfile.ClassPool.classesAccept(ClassPool.java:218) ~[proguard-core-9.1.10.jar:9.1.10]
	at proguard.obfuscate.Obfuscator.execute(Obfuscator.java:297) ~[proguard-base-7.7.0.jar:7.7.0]
	at proguard.pass.PassRunner.run(PassRunner.java:24) ~[proguard-base-7.7.0.jar:7.7.0]
	at proguard.ProGuard.obfuscate(ProGuard.java:500) ~[proguard-base-7.7.0.jar:7.7.0]
	at proguard.ProGuard.execute(ProGuard.java:211) ~[proguard-base-7.7.0.jar:7.7.0]
	at proguard.ProGuard.main(ProGuard.java:649) [proguard-base-7.7.0.jar:7.7.0]

```

**Comment by ketan** [comment]
After further investigation, I was able to narrow the issue down to the class below. It appears that ProGuard is having trouble processing `com.fasterxml.jackson.module.kotlin.readValue` correctly. I'm using proguard 7.7, with proguard-core 9.1.10, and jackson (with kotlin module) v2.19.2.


```kotlin
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import jakarta.persistence.AttributeConverter
import jakarta.persistence.Converter

@Converter(autoApply = false)
class StringCollectionToJsonConverter : AttributeConverter<Collection<String>, String> {
    private val objectMapper = ObjectMapper().registerKotlinModule()

    override fun convertToDatabaseColumn(attribute: Collection<String>?): String {
        return objectMapper.writeValueAsString(attribute ?: emptyList<String>())
    }

    override fun convertToEntityAttribute(dbData: String?): Collection<String> {
        return if (dbData.isNullOrBlank()) emptyList() else objectMapper.readValue(dbData)
    }
}
```

the following change to the class resolves the problem:

```patch
+import com.fasterxml.jackson.core.type.TypeReference
 import com.fasterxml.jackson.databind.ObjectMapper
-import com.fasterxml.jackson.module.kotlin.readValue
 import com.fasterxml.jackson.module.kotlin.registerKotlinModule
 import jakarta.persistence.AttributeConverter
 import jakarta.persistence.Converter
@@ -15,6 +15,6 @@ class StringCollectionToJsonConverter : AttributeConverter<Collection<String>, S
     }
 
     override fun convertToEntityAttribute(dbData: String?): Collection<String> {
-        return if (dbData.isNullOrBlank()) emptyList() else objectMapper.readValue(dbData)
+        return if (dbData.isNullOrBlank()) emptyList() else objectMapper.readValue(dbData, object : TypeReference<List<String>>() {})
     }
 }
```
