### ISSUE TITLE
[7.1.0-beta2] java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by boris-petrov** [Guardsquare/proguard#143]
`7.1.0-beta1` works fine. Updating to `7.1.0-beta2` causes:

```
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at proguard.ClassPath.get(ClassPath.java:77)
        at proguard.ConfigurationChecker.check(ConfigurationChecker.java:65)
        at proguard.ProGuard.execute(ProGuard.java:95)
        at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1383)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
...
```

**Comment by mrjameshamilton** [comment]
Hi @boris-petrov ! Could you share your `ProGuardTask` definition? It looks like maybe there are no `-injars` or they have not been picked up for some reason. There was a refactoring of the `ProGuardTask` which could have introduced this problem.

**Comment by boris-petrov** [comment]
@mrjameshamilton - thanks for the support.

Well, the relevant pieces (concerning `injars`) are two:

```gradle
sourceSets.flatten().toSet().forEach { injars it.output }

...

def webAppDirName = "${projectDir}/src/web/webapp"

...

doFirst {
  injars webAppDirName
  outjars "${outputDirectory}/webapp"
}
```

The full definition of the task is rather big and I prefer to not put it here if possible. Please tell me if you need more information. Are you sure the problem concerns `injars`?

**Comment by mrjameshamilton** [comment]
The problem is actually how you're using the `ProGuardTask` - the task should be fully configured before it executes, while this is adding configuration *during* the task execution:

```
doFirst {
  injars webAppDirName
  outjars "${outputDirectory}/webapp"
}
```

Coincidentally, it worked previously, but it would not have been recommended. In future Gradle versions this type of mutation (changing task inputs during execution) will be prohibited.

Can you refactor your task? What was the reason that you use the `doFirst`?

**Comment by boris-petrov** [comment]
Ah, OK, I didn't know this.

So, one reason I'm doing this in a `doFirst` is because ProGuard doesn't work if the output directory already exists (I get a `Cannot write to file '/home/boris/code/project/build/obfuscated-war/webapp' specified for property 'outJarFileCollection' as it is a directory.`) so I have a `doFirst { delete outputDirectory }` in my task's definition.

Another thing I do is I have a few ProGuard tasks and some of them share the same config. So I have a function that does something like:

```gradle
def commonProGuardOptions = { sourceSets -> { ->
    ...
    sourceSets.flatten().toSet().forEach { injars it.output }
    ...
}

tasks.register('proguardWar', ProGuardTask) {
    ...
    def outputDirectory = "${buildDir}/obfuscated-war"
    doFirst { delete outputDirectory }
    doFirst commonProGuardOptions(...)
    doFirst {
        injars webAppDirName
        outjars "${outputDirectory}/webapp"
    }
}
```

Removing the last `doFirst` that you see seems to work - i.e. build fine (I haven't tried the result though), however removing the one before `commonProGuardOptions` leads to `java.io.IOException: The input doesn't contain any classes. Did you specify the proper '-injars' options?`. That's on both `beta1` and `beta2`. Not sure how I am supposed to do those things?

Thanks for the support!

**Comment by mrjameshamilton** [comment]
The major refactor of the `ProGuardTask` has been rolled back for now, so this shouldn't be a problem anymore. 7.1.0-beta3 has been released.

**Comment by boris-petrov** [comment]
@mrjameshamilton - thank you for the information! Is that temporary though? That is, are you going to again do this refactoring and will that mean that sooner or later what I do is not going to work? If so, what can I do about it given the use-cases I've outlined above? Thank you!
