### ISSUE TITLE
Internal problem starting the ProGuard GUI

### ISSUE THREAD

**Issue by epris** [Guardsquare/proguard#144]
Hello,

When I run `bin/proguardgui.sh` I obtain the following error
`  Internal problem starting the ProGuard GUI (Can't find resource for bundle java.util.PropertyResourceBundle, key field_generalization_classTip)
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key field_generalization_classTip
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at proguard.gui.GUIResources.getMessage(GUIResources.java:43)
	at proguard.gui.OptimizationsDialog.msg(OptimizationsDialog.java:249)
	at proguard.gui.OptimizationsDialog.tip(OptimizationsDialog.java:237)
	at proguard.gui.OptimizationsDialog.<init>(OptimizationsDialog.java:126)
	at proguard.gui.ProGuardGUI.createOptimizationsButton(ProGuardGUI.java:984)
	at proguard.gui.ProGuardGUI.<init>(ProGuardGUI.java:444)
	at proguard.gui.ProGuardGUI$6.run(ProGuardGUI.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

I have

1.  Downloaded ProGuard-Core and I have built it with `gradle clean assemble`
2. Dowloaded Proguard and I have built libs with `./gradlew --include-build=../proguard-core assemble`
3. I'm suing macOSX
4. Java virtual machine is java 15.0.1 2020-10-20

**Comment by mrjameshamilton** [comment]
Hi @epris ! thanks for the report! This is an issue introduced in beta2 where we added some new optimizations but did not take into account the GUI app.

7.0.1 and 7.1.0-beta1 should work OK.

**Comment by mrjameshamilton** [comment]
Hi @epris , this should be fixed now on the master branch!
