### ISSUE TITLE
v6.0.3 java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by huopochuan** [Guardsquare/proguard#2]
java.lang.ArrayIndexOutOfBoundsException: -1
	at proguard.evaluation.Stack.getTop(Stack.java:216)
	at proguard.optimize.info.ParameterEscapeMarker.markEscapingParameters(ParameterEscapeMarker.java:457)
	at proguard.optimize.info.ParameterEscapeMarker.visitParameter(ParameterEscapeMarker.java:427)
	at proguard.classfile.util.AllParameterVisitor.visitParameters(AllParameterVisitor.java:178)
	at proguard.classfile.util.AllParameterVisitor.visitProgramMethod(AllParameterVisitor.java:72)
	at proguard.classfile.ProgramMethod.accept(ProgramMethod.java:93)
	at proguard.classfile.ProgramMember.accept(ProgramMember.java:125)
	at proguard.classfile.constant.RefConstant.referencedMemberAccept(RefConstant.java:126)
	at proguard.optimize.info.ParameterEscapeMarker.visitAnyMethodrefConstant(ParameterEscapeMarker.java:408)

**Comment by EricLafortune** [comment]
Thanks for your report. Can you check if this still happens in ProGuard 6.1.0 ? Do you perhaps have a sample that reproduces the problem?

**Comment by huopochuan** [comment]
thanks for your reply .it happens in ProGuard 6.0.3 and how to fix it.

**Comment by mrjameshamilton** [comment]
Hi @huopochuan, we'll close this old issue now but if you still have the issue with ProGuard 7.0.1 please re-open with a sample that reproduces the problem and we'll be able to investigate.
