### ISSUE TITLE
VarHandle.getAndAdd breaks going from 7.1.1 to 7.2.1

### ISSUE THREAD

**Issue by plexiq** [Guardsquare/proguard#221]
Obfuscation fails in 7.2.1 when using the getAndAdd method of a double[] VarHandle.

We are using the following pattern:
```
static final VarHandle arrayHandle = MethodHandles.arrayElementVarHandle(double[].class);

public void someMethod(double[] array){
   double c = 1.0 + (double) arrayHandle.getAndAdd(array, 0, 1.0);
   //do some other stuff
}
```

We can build the project without problems using proguard 7.1.1, the exact same code fails to obfuscate with 7.2.1 with the following warning and exception:
```
 [proguard] Warning:  [classname]:  can't find referenced method 'double getAndAdd(double[],int,double)' in library class java.lang.invoke.VarHandle
 [proguard] Exception in thread "main" java.lang.NoClassDefFoundError: proguard/classfile/visitor/FilteredClassVisitor
 [proguard]     at proguard.ClassSpecificationVisitorFactory.createClassPoolVisitor(ClassSpecificationVisitorFactory.java:253)
 [proguard]     at proguard.KeepClassSpecificationVisitorFactory.createClassPoolVisitor(KeepClassSpecificationVisitorFactory.java:284)
 [proguard]     at proguard.KeepClassSpecificationVisitorFactory.createClassPoolVisitor(KeepClassSpecificationVisitorFactory.java:214)
 [proguard]     at proguard.KeepClassSpecificationVisitorFactory.createClassPoolVisitor(KeepClassSpecificationVisitorFactory.java:102)
 [proguard]     at proguard.DescriptorKeepChecker.checkClassSpecifications(DescriptorKeepChecker.java:77)
 [proguard]     at proguard.Initializer.execute(Initializer.java:340)
 [proguard]     at proguard.pass.PassRunner.run(PassRunner.java:24)
 [proguard]     at proguard.ProGuard.initialize(ProGuard.java:328)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:130)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:614)
 [proguard] Caused by: java.lang.ClassNotFoundException: proguard.classfile.visitor.FilteredClassVisitor
 [proguard]     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
 [proguard]     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
 [proguard]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

```
Is this a bug or do we need to update our configuration? I couldn't find anything relevant in the changelog.

**Comment by plexiq** [comment]
Sorry, you can disregard/delete this. The exceptions were resolved by updating our maven configuration.

The warnings regarding getAndAdd are still there, we actually just overlooked them in 7.1.1. because the build worked otherwise. The build works again in 7.2.1 despite the warnings, we just had to resolve the exceptions.
