### ISSUE TITLE
NPE while copying resources from program jar

### ISSUE THREAD

**Issue by phileo99** [Guardsquare/proguard#224]
kotlin_version = '1.5.21'
classpath 'com.guardsquare:proguard-gradle:7.2.0'
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

```
Preparing output jar [ <<PROJECT_HOME>>/ProguardTransform/debug/92.jar] (filtered)
Preparing output jar [<<PROJECT_HOME>>/ProguardTransform/debug/0.jar] (filtered)
  Copying resources from program jar [<USER>/.gradle/caches/transforms-2/files-2.1/7893460a6b7c902a34709406c9c2af4f/jetified-fluentui_drawer-0.0.15-runtime.jar] (filtered)

> Task :azure-communication-ui-demo-app:transformClassesAndResourcesWithProguardTransformForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':azure-communication-ui-demo-app:transformClassesAndResourcesWithProguardTransformForDebug'.
> java.lang.NullPointerException

java.lang.NullPointerException
        at proguard.classfile.util.ClassUtil.externalClassName(ClassUtil.java:212)
        at proguard.io.ClassMapDataEntryReplacer.writeClassMap(ClassMapDataEntryReplacer.java:99)
        at proguard.io.ClassMapDataEntryReplacer.read(ClassMapDataEntryReplacer.java:75)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85)
        at proguard.io.ExtraDataEntryReader.readExtraEntries(ExtraDataEntryReader.java:150)
        at proguard.io.ExtraDataEntryReader.read(ExtraDataEntryReader.java:123)
        at proguard.io.RenamedDataEntryReader.read(RenamedDataEntryReader.java:97)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:85)
        at proguard.io.JarReader.read(JarReader.java:84)
        at proguard.io.DirectorySource.readFiles(DirectorySource.java:68)
        at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54)
        at proguard.InputReader.readInput(InputReader.java:264)
        at proguard.InputReader.readInput(InputReader.java:232)
        at proguard.OutputWriter.writeOutput(OutputWriter.java:410)
        at proguard.OutputWriter.execute(OutputWriter.java:148)
        at proguard.ProGuard.writeOutput(ProGuard.java:600)
        at proguard.ProGuard.execute(ProGuard.java:261)
        at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1424)
        at proguard.gradle.plugin.android.ProGuardTransform.transform(ProGuardTransform.kt:93)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
```

**Comment by mrjameshamilton** [comment]
Hi @phileo99 !

Are you able to provide a reproducible sample?

From the stacktrace alone, It looks like it's related to `-addconfigurationdebugging`; it seems that a superclass name is null. Are you using that option? If you remove the option does it work? Do you get any warnings in the log about missing classes?

**Comment by phileo99** [comment]
if I remove `-addconfigurationdebugging` then it no longer crashes.
Also theer are no warnings in the log about missing classes

**Comment by runforprogram** [comment]
also happy
