### ISSUE TITLE
Unable to open nested entry jar since it is compressed

### ISSUE THREAD

**Issue by abhisheksurve45** [Guardsquare/proguard#308]
Proguard version: 7.2.2

Proguard config:

```xml
<plugin>
    <groupId>com.github.wvengen</groupId>
    <artifactId>proguard-maven-plugin</artifactId>
    <version>${proguard.maven.plugin.version}</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>proguard</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <injar>${project.build.finalName}.jar</injar>
        <outjar>${project.build.finalName}.jar</outjar>
        <obfuscate>true</obfuscate>
        <attach>true</attach>
        <proguardInclude>${project.basedir}/proguard.cfg</proguardInclude>
        <injarNotExistsSkip>true</injarNotExistsSkip>
        <libs>
            <lib>${java.home}/jmods/</lib>
        </libs>
    </configuration>
</plugin>
```

```
-target 11 ## Specify the java version number
-dontshrink ## Default is enabled, here the shrink is turned off, that is, the unused classes/members are not deleted.
-dontoptimize ## Default is enabled, here to turn off bytecode level optimization
-useuniqueclassmembernames ## Take a unique strategy for confusing the naming of class members
-adaptclassstrings ## After confusing the class name, replace it with a place like Class.forName('className')
-dontnote
-ignorewarnings ## warnings are ignored
-dontwarn
-keep public class * extends org.springframework.boot.web.support.SpringBootServletInitializer
-keepdirectories ## Keep the package structure
-keepclasseswithmembers public class * { public static void main(java.lang.String[]);} ##Maintain the class of the main method and its method name
-keepclassmembers enum * { *; }  ## Reserving enumeration members and methods
-keepclassmembers class * {
     @org.springframework.beans.factory.annotation.Autowired *;
     @org.springframework.beans.factory.annotation.Qualifier *;
     @org.springframework.beans.factory.annotation.Value *;
     @org.springframework.beans.factory.annotation.Required *;
     @org.springframework.context.annotation.Bean *;
     @org.springframework.context.annotation.Primary *;
     @org.springframework.boot.context.properties.ConfigurationProperties *;
     @org.springframework.boot.context.properties.EnableConfigurationProperties *;
     @javax.inject.Inject *;
     @javax.annotation.PostConstruct *;
     @javax.annotation.PreDestroy *;
}
-keep @org.springframework.cache.annotation.EnableCaching class *
-keep @org.springframework.context.annotation.Configuration class *
-keep @org.springframework.boot.context.properties.ConfigurationProperties class *
-keep @org.springframework.boot.autoconfigure.SpringBootApplication class *
-allowaccessmodification
-keepattributes *Annotation*
-keepdirectories com.test.demo
-keepdirectories org.springframework.boot.autoconfigure
-keepclassmembers class * {
    *** get*();
    void set*(***);
}
-keepclassmembernames class * {
     java.lang.Class class$(java.lang.String);
     java.lang.Class class$(java.lang.String, boolean);
}
-keepclassmembers enum * {
     public static **[] values();
     public static ** valueOf(java.lang.String);
     public static ** fromValue(java.lang.String);
}
-keepnames class * implements java.io.Serializable
-keepclassmembers class * implements java.io.Serializable {
     static final long serialVersionUID;
     private static final java.io.ObjectStreamField[] serialPersistentFields;
     !static !transient <fields>;
     !private <fields>;
     !private <methods>;
     private void writeObject(java.io.ObjectOutputStream);
     private void readObject(java.io.ObjectInputStream);
     java.lang.Object writeReplace();
     java.lang.Object readResolve();
}
-keepclassmembers class * {
     @org.springframework.beans.factory.annotation.Autowired <fields>;
     @org.springframework.beans.factory.annotation.Autowired <methods>;
     @org.springframework.security.access.prepost.PreAuthorize <methods>;
}

```

The jar is getting generated however while run it via

```
java -jar demo-1.0.jar
```

Getting below error

Error:

```
Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/common-1.0.0.jar
      at org.springframework.boot.loader.a.j.f(Unknown Source)
      at org.springframework.boot.loader.a.n.i(Unknown Source)
      at org.springframework.boot.loader.a.n.g(Unknown Source)
      at org.springframework.boot.loader.a.k.next(Unknown Source)
      at org.springframework.boot.loader.b.a(Unknown Source)
      at org.springframework.boot.loader.d.b(Unknown Source)
      at org.springframework.boot.loader.JarLauncher.main(Unknown Source)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/common-1.0.0.jar'
      at org.springframework.boot.loader.jar.o.a(Unknown Source)
      at org.springframework.boot.loader.jar.o.a(Unknown Source)
      ... 7 more
Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/common-1.0.0.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
      at org.springframework.boot.loader.jar.o.d(Unknown Source)
      at org.springframework.boot.loader.jar.o.b(Unknown Source)
      ... 9 more

```

**Comment by abhisheksurve45** [comment]
It is a maven multimodule project where

```
Root
|
----- A
|
----- B
|
----- C
```

where B imports A as a dependency and I'm trying to run proguard on B.

**Comment by abhisheksurve45** [comment]
Any update?

**Comment by mrjameshamilton** [comment]
Hi @abhisheksurve45 ! There is an [option](https://github.com/Guardsquare/proguard/blob/master/base/src/main/java/proguard/ConfigurationParser.java#L162) which looks like it's missing from the manual which might help in your usecase: possibly something like the following will help `-dontcompress BOOT-INF/lib/*.jar`

**Comment by abhisheksurve45** [comment]
Thanks @mrjameshamilton, will try it out.
