### ISSUE TITLE
Kotlin 1.8 Null Pointer Exception When Focused BasicTextField

### ISSUE THREAD

**Issue by mehmetakify** [Guardsquare/proguard#312]
After clicking jetpack compose `BasicTextField` composable, app crashes and give `Null Pointer Exception` at `kotlin.reflect.TypesJVMKt`. `onFocusChanged` modifier is also used, maybe there is a relation.

When all codebase are the same:

- Proguard 7.2.2 with Kotlin 1.7.20 works correctly.
- Proguard 7.3.1 with Kotlin 1.8.0 crashes.

**Comment by mrjameshamilton** [comment]
Hi @mehmetakify! Please check through the [troubleshooting section](https://www.guardsquare.com/manual/troubleshooting/troubleshooting) of the manual.

If that doesn't help, try adding keep rules for the problem class and methods.

If that doesn't help, please provide a fully reproducible sample.

**Comment by mehmetakify** [comment]
Hi, I realized that `androidx.compose.material:material:1.4.0-alpha05` causes the error and after downgrade to previous version `androidx.compose.material:material:1.4.0-alpha04` everything works. 

Run time error after click this component:

`BasicTextField(
        modifier = modifier
            .onPreviewKeyEvent {
                if ((it.key == Key.Enter || it.key == Key.NumPadEnter)) {
                    focusManager.clearFocus()
                    action()
                    true
                } else false
            }
            .fillMaxWidth()
            .onFocusChanged { placeholderText.value = if (it.isFocused) "" else placeholder },
        value = valueState.value,
        enabled = isEnabled,
        singleLine = true,
        textStyle = MaterialTheme.typography.h6.copy(
            color = textColor,
            textAlign = TextAlign.Start
        ),
        keyboardOptions = keyboardOptions,
        keyboardActions = KeyboardActions(
            onDone = {
                focusManager.clearFocus()
                action()
            }),
        visualTransformation = if (isPinCode) PasswordVisualTransformation() else VisualTransformation.None,
        onValueChange = { valueChangeAction(it) },
        decorationBox = { innerTextField ->
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.Start,
                modifier = Modifier
                    .clip(shape = RoundedCornerShape(6.dp))
            ) {
                if (valueState.value.text.isEmpty())
                    Text(
                        text = placeholderText.value
                    )
                innerTextField()
            }
        }
    )`
    
    Debug version works, minified version crashes. I keep all node classes `-keep class androidx.compose.ui.node.** { *; }` and get this error:
    
    `java.lang.NullPointerException
                                                                                                    	at androidx.compose.ui.node.DelegatableNodeKt.requireCoordinator-64DMado(Unknown Source:13)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.dispatchOnPositionedCallbacks$ui_release(Unknown Source:67)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(Unknown Source:0)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(Unknown Source:21)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(Unknown Source:21)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(Unknown Source:21)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(Unknown Source:21)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(Unknown Source:21)
                                                                                                    	at androidx.compose.ui.node.OnPositionedDispatcher.dispatch(Unknown Source:45)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(Unknown Source:11)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks$default(Unknown Source:5)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(Unknown Source:27)
                                                                                                    	at androidx.compose.ui.node.Owner.measureAndLayout$default(Unknown Source:7)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:21)
                                                                                                    	at android.view.View.draw(View.java:23901)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22767)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22714)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22714)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22714)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22714)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5432)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5140)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4204)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2911)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10481)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:797)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`
