### ISSUE TITLE
Unexpected 'IOException' when trying to obfuscate using Zulu JDK 11 and Maven

### ISSUE THREAD

**Issue by Kawaxte** [Guardsquare/proguard#361]
When using `proguard-maven-plugin` in a Java 11 project, which utilises `proguard-base-7.2.2` and `proguard-core-9.0.1`, the following ERROR is shown at the end of the obfuscation attempt:
```java
 [proguard] Unexpected error
 [proguard] java.io.IOException: Missing closing quote for ''C:\Program' in argument number 50
 [proguard] 	at proguard.WordReader.nextWord(WordReader.java:233) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ConfigurationParser.readNextWord(ConfigurationParser.java:1844) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ConfigurationParser.readNextWord(ConfigurationParser.java:1820) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ConfigurationParser.parseClassPathArgument(ConfigurationParser.java:328) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ConfigurationParser.parse(ConfigurationParser.java:156) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:619) [proguard-base-7.2.2.jar:7.2.2]
 ```
 
 For proguard configuration, the following code is used:
 ```xml
       <plugin>
        <!-- https://mvnrepository.com/artifact/com.github.wvengen/proguard-maven-plugin -->
        <artifactId>proguard-maven-plugin</artifactId>
        <configuration>
          <injar>${project.build.finalName}.jar</injar>
          <libs>
            <lib>${java.home}/jmods/java.base.jmod"</lib>
            <lib>${java.home}/jmods/java.desktop.jmod"</lib>
          </libs>
          <outjar>${project.build.finalName}.jar</outjar>
          <proguardInclude>${project.basedir}/proguard.conf</proguardInclude>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>proguard</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
        <groupId>com.github.wvengen</groupId>
        <version>2.6.0</version>
      </plugin>
```

**Comment by mrjameshamilton** [comment]
Hi @Kawaxte !

The maven plugin project is not supported by Guardsquare. That project can be found here: https://github.com/wvengen/proguard-maven-plugin .
