### ISSUE TITLE
java.lang.VerifyError: Expecting a stackmap frame at branch target 14

### ISSUE THREAD

**Issue by kodewithaayush** [Guardsquare/proguard#411]
Hi Team,

While obfuscation my Shadow Jar which is dependent on multiple modules I have added rule to keep class inside one package 
-keep class com.service.** {
   *;
}
Still I can see that proguard is modifying the byteCode irrespective of using above rule.

I have tried everything like 
-dontshrink
-dontoptimize
-dontpreverify

also used 
-keepattributes SourceFile,ConstantValue,LineNumberTable,RuntimeVisibleAnnotations,RuntimeInvisibleAnnotations,RuntimeVisibleParameterAnnotations,RuntimeInvisibleParameterAnnotations,StackMapTable,EnclosingMethod

ERROR BELOW:

java.lang.VerifyError: Expecting a stackmap frame at branch target 14
Exception Details:
  Location:
    com//service/Service.$getStaticMetaClass()Lgroovy/lang/MetaClass; @6: if_acmpeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2ab6 005e 1207 a500 082a b800 63b0 b200
    0000010: 224c 2bc7 000f 2ab6 005e b800 6059 4cb3
    0000020: 0022 2bb6 0061 b0        
    

I believe Proguard should not change the byteCode of the class file if I use to -keep it using pro rule.

Sample Bytecode is attached showing obfuscated and original class file.

[KryoFactory_getKryoInstance_closure1_obfuscate.txt](https://github.com/user-attachments/files/15537884/KryoFactory_getKryoInstance_closure1_obfuscate.txt)
[KryoFactory_getKryoInstance_closure1_original.txt](https://github.com/user-attachments/files/15537887/KryoFactory_getKryoInstance_closure1_original.txt)

    Could you please help me with the solution if I am missing something.

**Comment by kodewithaayush** [comment]
Update:

I was able to resolve this.
Now I am facing another issue while deserialization

I just want to obfuscate one package and want to keep rest of my classes as it is, still I guess proguard is modifying the byte code of the class I added as Keep in the pro rules.
java.lang.IllegalStateException: unread block data
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:3033)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1722)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2496)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2390)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2228)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:489)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:447)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:507)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

Thanks in advance

**Comment by mrjameshamilton** [comment]
If you're running code on the JVM then you must preverify the classes: so you should remove `-dontpreverify` from the configuration.

If you enable any of shrinking, optimization or obfuscation, then the stackmap frames are removed at the beginning of ProGuard [here](https://github.com/Guardsquare/proguard/blob/master/base/src/main/java/proguard/ProGuard.java#L125).

The preverification is then executed at the end of ProGuard to recompute the stackmap frames after any modifications that ProGuard would have made due to shrinking, optimization or obfuscation [here](https://github.com/Guardsquare/proguard/blob/master/base/src/main/java/proguard/ProGuard.java#L232).

It's not clear how your problem is related to your configuration though. Can you provide a reproducible sample?

**Comment by nthieu90** [comment]
Hi @mrjameshamilton,
I tried to remove `-dontpreverify`, but the StackMapTable is still gone. 
I'm using DexGuard 6.0.24.
