### ISSUE TITLE
StackOverflowException when obfuscating pattern matching switch

### ISSUE THREAD

**Issue by boq** [Guardsquare/proguard#444]
Replicated in Proguard 7.6.0 and JDK 21.0.2.

Reproduction case:
```java
public class SwitchTest {
    public interface Type {
    }

    public enum Types implements Type {A}

    public static String test(final Type type) {
        return switch (type) {
            case Types.A -> "a";
            default -> "?";
        };
    }
}
```

Repeated stacktrace section looks like this:
```
	at proguard.classfile.ProgramClass.attributesAccept(ProgramClass.java:613)
	at proguard.classfile.editor.ConstantPoolShrinker.visitDynamicConstant(ConstantPoolShrinker.java:142)
	at proguard.classfile.constant.DynamicConstant.accept(DynamicConstant.java:109)
	at proguard.classfile.ProgramClass.constantPoolEntryAccept(ProgramClass.java:555)
	at proguard.classfile.attribute.BootstrapMethodInfo.methodArgumentsAccept(BootstrapMethodInfo.java:57)
	at proguard.classfile.editor.ConstantPoolShrinker.visitBootstrapMethodInfo(ConstantPoolShrinker.java:403)
	at proguard.classfile.attribute.BootstrapMethodsAttribute.bootstrapMethodEntriesAccept(BootstrapMethodsAttribute.java:58)
	at proguard.classfile.editor.ConstantPoolShrinker.visitBootstrapMethodsAttribute(ConstantPoolShrinker.java:209)
	at proguard.classfile.attribute.BootstrapMethodsAttribute.accept(BootstrapMethodsAttribute.java:49)
	at proguard.classfile.ProgramClass.attributesAccept(ProgramClass.java:613)
```

It seems to be triggered by `Dynamic` entry (and probably `InvokeDynamic`) in any of the arguments in `BootstrapMethods` attribute. Code in `visitDynamicConstant` seems to pass visitor back to class, which visits all attributes, eventually running back into `BootstrapMethods` and repeating whole process.

**Comment by rgaschy** [comment]
I've encountered the exact same issue.
It can still be reproduced on proguard 7.6.1 and JDK 21.0.2.
Here attached is a simple project that allows to reproduce the issue:
- unzip it
- run gradlew obfuscate --stacktrace
(Basically, it wraps the class above in a gradle project)

[proguard.zip](https://github.com/user-attachments/files/18349696/proguard.zip)

Would you please have a look at this issue?

**Comment by piazzesiNiccolo-GS** [comment]
Fixed by ef6a8352bdbbf233e21a9dee5e5f9ac394cb7fc3
