### ISSUE TITLE
Proguard fails to modify scope of function accessed by method reference in class that is being repackaged

### ISSUE THREAD

**Issue by yhartanto** [Guardsquare/proguard#65]
**Issue**
This bug seems to occur with **-repackageclasses ''** and **-allowaccessmodification** config enabled. 

1. One class (Foo) uses Method Reference (::) to call a _package-private_ function of another class (Bar) in the same package 
2. Caller class (Foo) is obfuscated but the second class (Bar) is not.

**Expected behavior:**
function in Bar being called from Foo using method reference is modified its scope to be public because caller class (Foo) is now using unnamed package but target class (Bar) remains in the same package.

**Actual behavior:**
The said function remains package-protected and at runtime, the application throws IllegalAccessError because two classes in different package should not be able to access function of one another.

```
java.lang.IllegalAccessError: Method 'void a.a(int)' is inaccessible to class
```

**Reproduction**
1. Use this modified example of this repo https://github.com/yhartanto/proguard/tree/proguard_7
2. go to examples/android folder
3. run ./gradlew clean installRelease
4. The sample Application will now crash with a stacktrace below:

```
java.lang.IllegalAccessError: Method 'void a.a(int)' is inaccessible to class 'com.example.-$$Lambda$eXvvZ4ksZ0N6IX8OVDx6J_NW7dQ' (declaration of 'com.example.-$$Lambda$eXvvZ4ksZ0N6IX8OVDx6J_NW7dQ' appears in /data/app/~~lWowO2Q2RgqHi75LBko89w==/com.example-A_KsbmMRNxt10gfGmNj8cQ==/base.apk)
        at com.example.-$$Lambda$eXvvZ4ksZ0N6IX8OVDx6J_NW7dQ.accept(Unknown Source:8)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:604)
        at com.example.HelloWorldActivity.onCreate(Unknown Source:56)
        at android.app.Activity.performCreate(Activity.java:7995)
        at android.app.Activity.performCreate(Activity.java:7979)
```

**More information:**
In the modified example, I introduced a class called [FooBar](https://github.com/yhartanto/proguard/blob/proguard_7/examples/android/src/com/example/FooBar.java) and added repackageclasses and allowaccessmodification into the proguard config. FooBar includes a foo function that is called from the [HelloWorldActivity](https://github.com/yhartanto/proguard/blob/proguard_7/examples/android/src/com/example/HelloWorldActivity.java#L32) using Method Reference.
Because HelloWorldActivity name is kept and FooBar is obfuscated, their package names are now different and I would expect that the scope of Foo is moved to public.

This bug seems to exist since version 6, use this [branch](https://github.com/yhartanto/proguard/tree/proguard_6_2_2) and follow the same reproduction steps as above. 

Using [proguard 5](https://github.com/yhartanto/proguard/tree/proguard_5), you can follow the same steps and find that the behavior is what we expected. foo function is being modified into public allowing HelloWorldActivity to call it from another package.

**Comment by yhartanto** [comment]
Another hint that we know of is that using lambda pattern is a workaround for us right now `() ->` Although I notice that with lambda, the code is rewritten differently after obfuscation.

**Comment by kurtisnelson** [comment]
Any updates?
