### ISSUE TITLE
OutOfMemoryError at obsfucation step with a specific aar

### ISSUE THREAD

**Issue by yintaibing** [Guardsquare/proguard#73]
My android project is using Proguard v6.0.3. Usually 2G of memory is enough for a release build. 
But after upgrading a 3rd-party lib, building is failed:
```
> Task :app:transformClassesAndResourcesWithProguardForRelease
ProGuard, version 6.0.3
Reading input...
// Reading other jars
Reading program jar [C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\2758f3f993debb8a196bed9d9536ad80\jetified-shanyan_sdk_v2.4.2.0-runtime.jar] (filtered)
Reading program jar [E:\zhenai\zhenai_nearby\app\build\intermediates\merged_java_res\release\out.jar] (filtered)
Reading library jar [D:\android-sdk-windows\platforms\android-28\android.jar]
// Reading other jars
Note: there were 14 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 2 library classes explicitly being kept.
      You don't need to keep library classes; they are already left unchanged.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#libraryclass)
Note: there were 97 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Warning: there were 2 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Note: you're ignoring all warnings!
Ignoring unused library classes...
  Original number of library classes: 4803
  Final number of library classes:    2321

> Task :app:transformClassesAndResourcesWithProguardForRelease FAILED

FAILURE: Build failed with an exception.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        // other stacktrace
Caused by: java.lang.OutOfMemoryError: Java heap space
        at proguard.evaluation.Stack.reset(Stack.java:85)
        at proguard.evaluation.TracedStack.reset(TracedStack.java:135)
        at proguard.optimize.evaluation.PartialEvaluator.initializeArrays(PartialEvaluator.java:1257)
        at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute0(PartialEvaluator.java:306)
        at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute(PartialEvaluator.java:230)
        at proguard.classfile.util.ArrayInitializationReplacer.visitCodeAttribute(ArrayInitializationReplacer.java:89)
        at proguard.classfile.util.ArrayInitializationReplacer$ArrayInitializationFilter.visitCodeAttribute(ArrayInitializationReplacer.java:196)
        at proguard.classfile.attribute.CodeAttribute.accept(CodeAttribute.java:141)
        at proguard.classfile.ProgramMethod.attributesAccept(ProgramMethod.java:101)
        at proguard.classfile.attribute.visitor.AllAttributeVisitor.visitProgramMember(AllAttributeVisitor.java:95)
        at proguard.classfile.util.SimplifiedVisitor.visitProgramMethod(SimplifiedVisitor.java:93)
        at proguard.classfile.ProgramMethod.accept(ProgramMethod.java:93)
        at proguard.classfile.ProgramClass.methodsAccept(ProgramClass.java:588)
        at proguard.classfile.util.ArrayInitializationReplacer.visitProgramClass(ArrayInitializationReplacer.java:73)
        at proguard.classfile.ProgramClass.accept(ProgramClass.java:430)
        at proguard.classfile.ClassPool.classesAccept(ClassPool.java:124)
        at proguard.ProGuard.introducePrimitiveArrayConstants(ProGuard.java:281)
        at proguard.ProGuard.execute(ProGuard.java:119)
        at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:66)
        // other stacktrace
```
My proguard-rules.pro file:
```
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
-dontoptimize
-dontpreverify
# Keep all classes in the 3rd-party lib
-dontwarn com.baidu.**
-dontwarn com.cmic.sso.sdk.**
-dontwarn com.unicom.xiaowo.account.shield.**
-dontwarn com.sdk.**
-dontwarn com.chuanglan.shanyan_sdk.**
-keep class com.cmic.sso.sdk.**{*;}
-keep class com.sdk.** { *;}
-keep class com.unicom.xiaowo.account.shield.** {*;}
-keep class cn.com.chinatelecom.account.api.**{*;}
-keep class com.chuanglan.shanyan_sdk.**{*;}
```
Some event in this issue:
1.The memory usage remains at 1g-2g before obsfucation step, that is the normal level. Then memory increase to 4g-6g in about 2 seconds, which is really fast and weird.

What I have tried but didn't work:
1.Keep all classes in the 3rd-party lib.
2.Upgrade Proguard to v7.0.0.

Finally I found 2 temporary solutions:
1.Use ```-dontobfuscate```, but it's unacceptable for a release apk.
2.Allocate at least 6G of memory to gradle, but it would occupy too much resources of the building machine, it's also unacceptable for the long term.

I have asked the provider of the 3rd-party lib but we found no suspicious problem. If anyone can help, I would be very grateful. Resource:
1.[The 3rd-party aar file](https://github.com/yintaibing/PublicResources/blob/master/shanyan_sdk_v2.4.2.0.aar)
2.[The jetified jar of the aar](https://github.com/yintaibing/PublicResources/blob/master/jetified-shanyan_sdk_v2.4.2.0-runtime.jar)
3.[MAT analyze report of Proguard dump](https://github.com/yintaibing/PublicResources/blob/master/java_pid10400_Leak_Suspects.zip)

**Comment by EricLafortune** [comment]
Thanks for your detailed report. The pre-obfuscated library class `com/unicom/xiaowo/account/shield/a/a` has a static intializer that creates and fills a large integer array of 4000 elements using 29621 bytes of instructions and an extremely large stack frame size of 4003 elements. It duplicates a reference value 4000 times on the stack.

Initialized primitive arrays (like `{ 1, 2, 3 }`) are notoriously inefficient in Java bytecode, because they are implemented by filling out the values one by one. This particular method implements it in an unusual way, unlike the other methods. ProGuard's initial analysis of array initializations ends up taking a lot of memory. We can investigate reducing it, but this is a very unusual piece of code.

**Comment by yintaibing** [comment]
@EricLafortune 
Thanks for your analysis and reply. I will tell the provider of the lib to see this issue. I will keep this issue open and following it.

**Comment by mrjameshamilton** [comment]
Hi @yintaibing, since the issue has been explained and is due to some very usual code, we'll close this issue now.
