### ISSUE TITLE
Correspondence between springboot version and proguard version

### ISSUE THREAD

**Issue by simonsfan** [Guardsquare/proguard#77]
**Hi , i use proguard-base（version 6.0.2）with maven in springboot（2.2.2.RELEASE）,it works fine.**

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.2.2.RELEASE</version>
</parent>
```

> <build>
        <plugins>
            <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.0.14</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <proguardVersion>6.0.2</proguardVersion>
                    <obfuscate>true</obfuscate>
                    <attachArtifactClassifier>pg</attachArtifactClassifier>
                    <options>
                        <option>-target 1.8</option>
                        <option>-dontshrink</option>
                        <option>-dontoptimize</option>
                        <option>-dontskipnonpubliclibraryclasses</option>
                        <option>-dontskipnonpubliclibraryclassmembers</option>
                        <option>-allowaccessmodification</option>
                        <option>-useuniqueclassmembernames</option>
                        <option>-adaptclassstrings</option>
                        <option>-dontusemixedcaseclassnames</option><option>-keeppackagenames</option>
                        <option>-keepparameternames</option>
                        <option>-keepattributes
                            Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod,LocalVariableTable,LocalVariableTypeTable,MethodParameters
                        </option>
                        <option>
                            -keepclassmembers public class *{void set*(***);*** get*();}
                        </option>
                        <option>
                            -keepclasseswithmembers public class * { public static void main(java.lang.String[]);}
                        </option>
                        <option>-keepclassmembers enum * { *; }</option>
                        <option>-keep class com.abc.framework.admin.sys.mapper.** { *; }</option>
                        <option>-keep class com.abc.framework.admin.sdk.** { *; }</option>
                        <option>-dontwarn **</option>
                    </options>
                    <libs>
                        <lib>${java.home}/lib/rt.jar</lib>
                    </libs>
                    <inFilter>com/abc/framework/admin/sys/**</inFilter>
                    <injar>classes</injar>
                    <injar>${project.build.finalName}.jar</injar>
                    <outjar>${project.build.finalName}-pg.jar</outjar>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.sf.proguard</groupId>
                        <artifactId>proguard-base</artifactId>
                        <version>6.0.2</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

**Recently，due to the spring boot version upgrade**：

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.3.3.RELEASE</version>
</parent>
```
**The following error occurred：**

>  [proguard] Reading library jar [D:\repository\com\github\virtuald\curvesapi\1.04\curvesapi-1.04.jar]java.io.IOException: Can't read [D:\repository\com\zaxxer\HikariCP\3.4.5\HikariCP-3.4.5.jar] (Can't process class [META-INF/versions/11/module-info.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))
 [proguard]     at proguard.InputReader.readInput(InputReader.java:214)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:184)
 [proguard]
 [proguard]     at proguard.InputReader.readInput(InputReader.java:162)
 [proguard]     at proguard.InputReader.execute(InputReader.java:114)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:255)
 [proguard] Reading library jar [D:\repository\cglib\cglib\3.1\cglib-3.1.jar]
 [proguard] Reading library jar [D:\repository\org\ow2\asm\asm\4.2\asm-4.2.jar] at proguard.ProGuard.execute(ProGuard.java:96)
 [proguard]
 [proguard]     at proguard.ProGuard.main(ProGuard.java:572)
 [proguard] Reading library jar [D:\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar]
 [proguard] Caused by: java.io.IOException: Can't process class [META-INF/versions/11/module-info.class] (Unsupported version number [55.0] (maximum 54.0, Java 10))
 [proguard] Reading library jar [D:\repository\org\ehcache\ehcache\3.8.1\ehcache-3.8.1.jar]
 [proguard]     at proguard.io.ClassReader.read(ClassReader.java:114)
 [proguard]     at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
 [proguard] Reading library jar [D:\repository\com\cpic\framework\admin\cpic-admin-sdk-ext-dataIncr\2.1.6-RELEASE\cpic-admin-sdk-ext-dataIncr-2.1.6-RELEASE.jar]
 [proguard]     at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
 [proguard]     at proguard.io.JarReader.read(JarReader.java:83)
 [proguard] Reading library jar [D:\repository\org\springframework\boot\spring-boot-autoconfigure\2.3.3.RELEASE\spring-boot-autoconfigure-2.3.3.RELEASE.jar]
 [proguard]     at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
 [proguard]     at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
 [proguard] Reading library jar [D:\repository\org\springframework\boot\spring-boot-starter-jdbc\2.3.3.RELEASE\spring-boot-starter-jdbc-2.3.3.RELEASE.jar]
 [proguard]     at proguard.InputReader.readInput(InputReader.java:210)
 [proguard]     ... 6 more
 [proguard] Reading library jar [D:\repository\com\zaxxer\HikariCP\3.4.5\HikariCP-3.4.5.jar]
 [proguard] Caused by: java.lang.UnsupportedOperationException: Unsupported version number [55.0] (maximum 54.0, Java 10)
 [proguard]     at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:150)
 [proguard]     at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:89)
 [proguard]     at proguard.classfile.LibraryClass.accept(LibraryClass.java:306)
 [proguard]     at proguard.io.ClassReader.read(ClassReader.java:86)
 [proguard]     ... 12 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.712s
[INFO] Finished at: Mon Sep 07 15:32:20 CST 2020
[INFO] Final Memory: 71M/1011M

it seems was the error of conflict between java version and HikariCP-3.4.5.jar，then i try:

> <option>-libraryjars  ${settings.localRepository}/com/zaxxer/HikariCP/3.4.5/HikariCP-3.4.5.jar(!META-INF/versions/11/module-info.class)</option>

but it did not take effect.

Is there a correspondence between the springboot version and the proguard version?*
Thanks for the answer~

**Comment by simonsfan** [comment]
I forced to use the dependency：
```
<dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
      <version>3.4.1</version>
</dependency>
```
it work fine~
