### ISSUE TITLE
Obfuscating aar with build with kotlin 1.4.10 throws java.lang.UnsupportedOperationException: Encountered corrupt @kotlin/Metadata

### ISSUE THREAD

**Issue by lsuski** [Guardsquare/proguard#84]
I'm trying to obfuscate aar with kotlin classes written in kotlin 1.4.10. The stacktrace is
```
Caused by: java.lang.UnsupportedOperationException: Encountered corrupt @kotlin/Metadata for class some/my/Class.
	at proguard.classfile.util.kotlin.KotlinMetadataInitializer.visitAnnotation(KotlinMetadataInitializer.java:92)
	at proguard.classfile.attribute.annotation.visitor.AnnotationTypeFilter.visitAnnotation(AnnotationTypeFilter.java:94)
	at proguard.classfile.attribute.annotation.AnnotationsAttribute.annotationsAccept(AnnotationsAttribute.java:77)
	at proguard.classfile.attribute.annotation.visitor.AllAnnotationVisitor.visitRuntimeVisibleAnnotationsAttribute(AllAnnotationVisitor.java:56)
	at proguard.classfile.attribute.visitor.AttributeNameFilter.visitRuntimeVisibleAnnotationsAttribute(AttributeNameFilter.java:365)
	at proguard.classfile.attribute.annotation.RuntimeVisibleAnnotationsAttribute.accept(RuntimeVisibleAnnotationsAttribute.java:53)
	at proguard.classfile.ProgramClass.attributesAccept(ProgramClass.java:726)
	at proguard.classfile.attribute.visitor.AllAttributeVisitor.visitProgramClass(AllAttributeVisitor.java:76)
	at proguard.classfile.ProgramClass.accept(ProgramClass.java:544)
	at proguard.classfile.ClassPool.classesAccept(ClassPool.java:276)
	at proguard.Initializer.execute(Initializer.java:179)
	at proguard.ProGuard.initialize(ProGuard.java:300)
	at proguard.ProGuard.execute(ProGuard.java:127)
	at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1344)
```

This could be related with https://youtrack.jetbrains.com/issue/KT-42107

**Comment by mrjameshamilton** [comment]
Hi @lsuski , we are aware of the problem and will release a fix soon!

**Comment by Reedyuk** [comment]
@mrjameshamilton any update with this?

**Comment by mrjameshamilton** [comment]
Sorry for the delay. We'll soon be publishing a version of ProGuard with the fix. Until then, as the fix is now in the [proguard-core](https://github.com/Guardsquare/proguard-core) repo, you could build ProGuard yourself: you'll have to check out both `proguard-core` and `proguard` and execute the following in the `proguard` project:

```
./gradlew --include-build ../proguard-core jar
```

**Comment by mrjameshamilton** [comment]
We've just released ProGuard 7.0.1 with the fix included!

**Comment by Reedyuk** [comment]
Thank you @mrjameshamilton!

**Comment by Reedyuk** [comment]
I have now found that the plugin has changed its name from 

```net.sf.proguard:proguard-gradle:6.3.0beta1```

to 

```com.guardsquare:proguard-gradle:7.0.1```
